-- Classroom Design Suite - Supabase/Postgres schema
-- Run this entire file once in Supabase Dashboard -> SQL Editor.

create table if not exists public.ilaw_user_keys (
  id bigint generated by default as identity primary key,
  label text not null,
  email text null,
  access_key text not null unique,
  password_hash text null,
  auth_provider text null default 'email',
  credit_limit integer null default 100 check (credit_limit is null or credit_limit >= 0),
  credits_used integer not null default 0 check (credits_used >= 0),
  ppt_credit_limit integer null default 20 check (ppt_credit_limit is null or ppt_credit_limit >= 0),
  ppt_credits_used integer not null default 0 check (ppt_credits_used >= 0),
  las_header_division text null,
  las_header_school_name text null,
  text_model text null,
  text_api_key text null,
  text_base_url text null,
  is_active boolean not null default true,
  notes text null,
  last_used_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_ilaw_user_keys_active on public.ilaw_user_keys (is_active);
create index if not exists idx_ilaw_user_keys_access on public.ilaw_user_keys (access_key);
create unique index if not exists idx_ilaw_user_keys_email_unique_ci
  on public.ilaw_user_keys (lower(email)) where email is not null and btrim(email) <> '';

create table if not exists public.ilaw_text_api_keys (
  id bigint generated by default as identity primary key,
  label text not null,
  provider text not null default 'OpenAI compatible',
  api_key text not null,
  model text null,
  base_url text null,
  priority integer not null default 100,
  is_active boolean not null default true,
  use_count integer not null default 0 check (use_count >= 0),
  last_used_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_ilaw_text_api_keys_active
  on public.ilaw_text_api_keys (is_active, priority, use_count);
create index if not exists idx_ilaw_text_api_keys_last_used on public.ilaw_text_api_keys (last_used_at);

create table if not exists public.ilaw_gamma_api_keys (
  id bigint generated by default as identity primary key,
  label text not null,
  api_key text not null,
  priority integer not null default 100,
  is_active boolean not null default true,
  use_count integer not null default 0 check (use_count >= 0),
  last_used_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_ilaw_gamma_api_keys_active
  on public.ilaw_gamma_api_keys (is_active, priority, use_count);
create index if not exists idx_ilaw_gamma_api_keys_last_used on public.ilaw_gamma_api_keys (last_used_at);

create table if not exists public.ilaw_gamma_generations (
  generation_id text primary key,
  gamma_key_id bigint null references public.ilaw_gamma_api_keys(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ilaw_global_settings (
  setting_key text primary key,
  setting_value text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ilaw_ppt_credit_charges (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.ilaw_user_keys(id) on delete cascade,
  generation_id text not null,
  credits_deducted integer not null default 0 check (credits_deducted >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, generation_id)
);

create index if not exists idx_ilaw_ppt_credit_charges_user on public.ilaw_ppt_credit_charges (user_id);
create index if not exists idx_ilaw_ppt_credit_charges_generation on public.ilaw_ppt_credit_charges (generation_id);

create table if not exists public.ilaw_email_otps (
  id bigint generated by default as identity primary key,
  email text not null,
  purpose text not null default 'signup',
  otp_hash text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz null,
  attempts integer not null default 0 check (attempts >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_ilaw_email_otps_lookup
  on public.ilaw_email_otps (email, purpose, consumed_at, expires_at);

-- Security hardening: these tables contain private application data/API keys.
-- The app uses a private server-side Postgres connection, so no browser-facing
-- anon/authenticated policies are required.
alter table public.ilaw_user_keys enable row level security;
alter table public.ilaw_text_api_keys enable row level security;
alter table public.ilaw_gamma_api_keys enable row level security;
alter table public.ilaw_gamma_generations enable row level security;
alter table public.ilaw_global_settings enable row level security;
alter table public.ilaw_ppt_credit_charges enable row level security;
alter table public.ilaw_email_otps enable row level security;

revoke all on table public.ilaw_user_keys from anon, authenticated;
revoke all on table public.ilaw_text_api_keys from anon, authenticated;
revoke all on table public.ilaw_gamma_api_keys from anon, authenticated;
revoke all on table public.ilaw_gamma_generations from anon, authenticated;
revoke all on table public.ilaw_global_settings from anon, authenticated;
revoke all on table public.ilaw_ppt_credit_charges from anon, authenticated;
revoke all on table public.ilaw_email_otps from anon, authenticated;

-- Durable serverless usage counters. These replace local JSON files that would
-- not persist reliably across Vercel function instances.
create table if not exists public.ilaw_global_usage (
  usage_date date primary key,
  count integer not null default 0 check (count >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.ilaw_gamma_credit_state (
  state_key text primary key,
  initial_credits integer null check (initial_credits is null or initial_credits >= 0),
  remaining integer null check (remaining is null or remaining >= 0),
  last_deducted integer null check (last_deducted is null or last_deducted >= 0),
  updated_at timestamptz not null default now(),
  last_generation_id text null
);

create table if not exists public.ilaw_gamma_credit_charges (
  generation_id text primary key,
  credits_deducted integer not null default 0 check (credits_deducted >= 0),
  created_at timestamptz not null default now()
);

alter table public.ilaw_global_usage enable row level security;
alter table public.ilaw_gamma_credit_state enable row level security;
alter table public.ilaw_gamma_credit_charges enable row level security;

revoke all on table public.ilaw_global_usage from anon, authenticated;
revoke all on table public.ilaw_gamma_credit_state from anon, authenticated;
revoke all on table public.ilaw_gamma_credit_charges from anon, authenticated;
